### PR TITLE
[3787] Update Police Offenses and Additional Offenses to accept multiple Charges

### PR DESCRIPTION
**Pull request by macrael**
## Description

This is the backend fix for the {police,additional} offenses work. 
The single shot test data (legal-police-offenses.json) was recreated fresh on the updated frontend, so it represents the correct structure there. Then the models, clearing no code, and templates were changed to be correct. Then all the test scenarios were updated. 

## Checklist for Reviewer

- [ ] Review code changes
- [ ] ideally, we'd check that this works with eQIP, but that might not be possible rn.

### CODE REVIEW

**Comment by macrael** [comment]
https://jira.devops.nbis.mil/jira/browse/EN-3787

**Comment by ryanhofdotgov** [comment]
@leonged @kdolan-soliel This is a significant change – would you both look at its Jira issue (EN-3787), it's companion Jira issue (EN-2417) that is resolved by PR #1867 and make sure you understand why it needed to be changed, and how they went about changing it? Thanks!

**Comment by ryanhofdotgov** [comment]
@leonged @kdolan-soliel  Ah never mind – I see that MacRae went over these issues with you already. Thanks!

**Comment by leonged** [comment]
@ryanhofdotgov i'm good on this, I've met with suz and mcrae over video conference going over the changes to frontend and backend

**Pull request merged**
